experiment_dir:
spec_file: prompt_specifications/specification_with_updated_nld.txt
failure_analysis_prompt: prompt_specifications/failure_analysis.txt
cfg_evolution_prompt: prompt_specifications/cfg_evolution.txt
tasks:
  - get[gem]
  - get[iron]
  - get[wood]  
  - get[grass]
  - get[gold]
  - make[plank] 
  - make[stick]
  - make[cloth]
  - make[rope]
  - make[bridge]
  - make[bundle]
  - make[flag]
  - make[bed]
  - make[axe]
  - make[shears]
  - make[ladder]
  - make[goldarrow]
max_dsl_evolutions: 2
max_function_evolutions: 0
total_samples: 1000
num_explicit_feedback_iterations: 30
max_attempts: 30
model_type: huggingface
recipes_path: craft/resources/recipes.yaml
hints_path: craft/resources/hints.yaml
skip_cfg_generation: false
cfg_output_file:
max_cfg_retries: 10
grid_regeneration_attempts: 15
use_existing_grid_specs: false
# grid_spec_dir: experiments/experiment_success/grids
